apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: cafk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cafk
    app.kubernetes.io/part-of: byoc-app-mcrv
  name: cafk
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: cafk
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: cafk
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-vrha-tenant/byoc-app-mcrv/cafk@sha256:48d44af091668180a5b51c74d9fbf0ca9f9c9c0bda9373bf53bfa12fa931733b
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
