apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: cafk
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: POC
          value: POC
        image: quay.io/redhat-appstudio-qe/byoc-vrha-tenant/byoc-app-mcrv/cafk@sha256:48d44af091668180a5b51c74d9fbf0ca9f9c9c0bda9373bf53bfa12fa931733b
        name: my-java-quarkus
        resources: {}
status: {}
