apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: cafk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cafk
    app.kubernetes.io/part-of: byoc-app-mcrv
  name: cafk
spec:
  rules:
  - host: cafk-byoc-vrha-tenant.apps.f4b17df51f8d5686c717.hypershift.aws-2.ci.openshift.org
    http:
      paths:
      - backend:
          service:
            name: cafk
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
